language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t savidude/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true savidude/docker-react npm run test
